# Generated by Django 5.1.1 on 2024-09-08 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 14, 15, 41, 214373, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
