# Generated by Django 5.1.1 on 2024-09-08 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 14, 20, 17, 905728, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
