# Generated by Django 5.1.1 on 2024-09-08 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 14, 42, 26, 665260, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
