# Generated by Django 5.1.1 on 2024-09-10 21:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaign_goal_campaign_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 21, 51, 10, 332382, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='video',
            field=models.FileField(null=True, upload_to='campaigns/videos/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mov', 'mpeg', 'avi', '3gp', 'wmv', 'flv', 'mp4'])], verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount'),
        ),
    ]
