# Generated by Django 5.1.1 on 2024-09-11 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_campaign_end_date_alter_campaign_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 19, 42, 16, 846340, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
