# Generated by Django 5.1.1 on 2024-09-13 04:23

import datetime
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 4, 23, 24, 444917, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1200, 800], upload_to='campaigns/%Y/%m', verbose_name='image'),
        ),
    ]
