# Generated by Django 5.1.1 on 2024-09-14 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 8, 36, 35, 448706, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
