# Generated by Django 4.1.11 on 2024-09-14 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_alter_campaign_end_date_alter_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 9, 36, 12, 127877, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
