# Generated by Django 4.1.11 on 2024-09-14 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 9, 36, 42, 722256, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
