# Generated by Django 4.1.11 on 2024-09-14 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_campaign_view_count_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 12, 44, 17, 833632, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
