# Generated by Django 4.1.11 on 2024-09-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_alter_campaign_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 12, 54, 19, 115084, tzinfo=datetime.timezone.utc), verbose_name='end date '),
        ),
    ]
