# Generated by Django 5.1.1 on 2024-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'error': 'Email exists!'}, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
