# Generated by Django 5.1.1 on 2024-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=256, verbose_name='campaign id')),
                ('goal_amount', models.IntegerField(verbose_name='goal amount')),
                ('raised_amount', models.DecimalField(decimal_places=19, max_digits=19, verbose_name='raised amount')),
                ('duration_days', models.IntegerField(verbose_name='duration days')),
                ('number_of_backers', models.IntegerField(verbose_name='number of backers')),
                ('category', models.CharField(max_length=256, verbose_name='category')),
                ('currency', models.CharField(max_length=256, verbose_name='currency')),
                ('owner_experience', models.IntegerField(verbose_name='owner experience')),
                ('is_video_included', models.BooleanField(verbose_name='campaign video is included')),
                ('social_media_presence', models.IntegerField(verbose_name='social media presence')),
                ('number_of_updates', models.IntegerField(verbose_name='number of updates')),
            ],
            options={
                'verbose_name': 'campaign data',
                'verbose_name_plural': 'campaign data',
                'db_table': 'campaign_data',
            },
        ),
    ]
