# Generated by Django 5.1.1 on 2024-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='is_video_included',
            field=models.CharField(max_length=256, verbose_name='campaign video is included'),
        ),
    ]
