# Generated by Django 5.1.1 on 2024-09-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_campaigndata_is_video_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='raised_amount',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='raised amount'),
        ),
    ]
