# Generated by Django 5.1.1 on 2024-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_campaigndata_raised_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, verbose_name='user id')),
                ('campaign_id', models.CharField(max_length=256, verbose_name='campaign id')),
                ('interaction_type', models.CharField(max_length=256, verbose_name='interaction_type')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'db_table': 'interaction',
            },
        ),
    ]
