# Generated by Django 5.1.1 on 2024-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_remove_campaigndata_social_media_presence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='user_id',
            field=models.CharField(default='default_user', max_length=256, verbose_name='user id'),
        ),
    ]
